# Generated by Django 4.2.8 on 2023-12-17 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('CategoriaID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ProductoID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MovimientosInventario',
            fields=[
                ('MovimientoID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField()),
                ('FechaMovimiento', models.DateTimeField()),
                ('TipoMovimiento', models.CharField(max_length=10)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosCategorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
            options={
                'unique_together': {('Producto', 'Categoria')},
            },
        ),
    ]
